name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Create a folder
      run: mkdir ./build

    - name: cd
      run: cd ./build
    
    - name: configure
      run: ../configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: qemu-${{matrix.compiler}}-${{matrix.arch}}-${{matrix.config}}-${{github.sha}}
